struct ExchangeRate
{
       string id;
       string from;
       string to;
       float32 rate;
       i64 timestamp;
       float32 ask;
       float32 bid;
};

service CurrencyExchange
{
    ExchangeRate lookup(string from, string to);
    //float convert(string from, string to, @Optional float32 value);
    float convert(string from, string to, float32 value);
};