struct ExchangeRate
{
       string id;
       string from;
       string to;
       float32 rate;
       i64 timestamp;
       float32 ask;
       float32 bid;
};

service CurrencyExchange
{
    ExchangeRate lookup(string fromCurrency, string toCurrency);
    //float convert(string fromCurrency, string toCurrency, @Optional float32 amount);
    float convert(string fromCurrency, string toCurrency, float32 amount);
};